CREATE TABLE Kategoriak (
  Nev STRING NOT NULL PRIMARY KEY
);

CREATE TABLE Kisallatok (
  ID LONG NOT NULL PRIMARY KEY,
  Nev STRING NOT NULL,
  Nem STRING NOT NULL,
  Eletkor INTEGER NOT NULL,
  Suly DECIMAL(3, 1) NOT NULL,
  Kategoria STRING NOT NULL,
  FOREIGN KEY (Kategoria) REFERENCES Kategoriak(Nev)
);